### ISSUE TITLE
Remove or fix upgrade.php

### ISSUE THREAD

**Issue by imarichev** [BeteLgis/moodle-qtype_digitalliteracy#6]
Few required fixes:
1. `if(true)` should be changed to `if($oldversion<xxxxxxxx)`
2. all operations with DB should be enclosed with tests for field existence, table existence and so on e.g:
`if( !$dbman->field_exists($table, $field_1) ){
            $dbman->add_field($table, $field_1); 
        }`

Actually, the upgrade.php script is needed only for upgrade purposes from one version to another.
So another option is to remove upgrade.php for now implying that this version is the first one to be publicly released.

**Comment by BeteLgis** [comment]
Fixed (couple weeks [commits] ago). upgrade.php was cleaned.
Actually, it should've never been uploaded to git - my bad cause it was just kind of a hotfix in a development stage.
Thanks!
